import { Injectable } from '@angular/core';


@Injectable({
  providedIn: 'root'
})
export class CalculosService {

  constructor() { }
  public calcularAenPd(lista:any[]):number{
    let suma:number=0
    if(lista[0]>0){
      suma=suma+(lista[0]-1);
    }
    if(lista[64]>0){
      suma=suma+(lista[64]-1);
    }
    if(lista[62]>0){
      suma=suma+(lista[62]-1);
    }
    if(lista[97]>0){
      suma=suma+(lista[97]-1);
    }
    if(lista[128]>0){
      suma=suma+(lista[128]-1);
    }
    if(lista[30]>0){
      suma=suma+((lista[30]-3)*-1);
    }
    if(lista[32]>0){
      suma=suma+((lista[32]-3)*-1);
    }
    if(lista[95]>0){
      suma=suma+((lista[32]-3)*-1);
    }
    if(lista[126]>0){
      suma=suma+((lista[126]-3)*-1);
    }
    if(lista[158]>0){
      suma=suma+((lista[158]-3)*-1);
    }
    if(lista[160]>0){
      suma=suma+((lista[160]-3)*-1);
    }
return suma

  }
  public calcularBenPd(lista:any[]):number{
    let suma:number=0
    if(lista[170]==1){
      suma=suma+1;
    }
    if(lista[171]==3){
      suma=suma+1;
    }
    if(lista[172]==1){
      suma=suma+1;
    }
    if(lista[173]==1){
      suma=suma+1;
    }
    if(lista[174]==3){
     suma=suma+1;
    }
    if(lista[175]==1){
      suma=suma+1;
    }
    if(lista[176]==2){
      suma=suma+1;
    }
    if(lista[177]==3){
      suma=suma+1;
    }
    if(lista[178]==3){
      suma=suma+1;
    }
    if(lista[179]==3){
      suma=suma+1;
    }
    if(lista[180]==2){
      suma=suma+1;
    }
    if(lista[181]==2){
      suma=suma+1;
    }
    if(lista[182]==2){
      suma=suma+1;
    }
    if(lista[183]==2){
      suma=suma+1;
    }
    if(lista[184]==2){
      suma=suma+1;
    }
return suma

  }
  public calcularCenPd(lista:any[]):number{
    let suma:number=0
    if(lista[31]>0){
      suma=suma+(lista[31]-1);
    }
    if(lista[34]>0){
      suma=suma+(lista[34]-1);
    }
    if(lista[66]>0){
      suma=suma+(lista[66]-1);
    }
    if(lista[130]>0){
      suma=suma+(lista[130]-1);
    }
    if(lista[1]>0){
      suma=suma+((lista[1]-3)*-1);
    }
    if(lista[63]>0){
      suma=suma+((lista[63]-3)*-1);
    }
    if(lista[96]>0){
      suma=suma+((lista[96]-3)*-1);
    }
    if(lista[127]>0){
      suma=suma+((lista[127]-3)*-1);
    }
    if(lista[159]>0){
      suma=suma+((lista[159]-3)*-1);
    }
    if(lista[161]>0){
      suma=suma+((lista[161]-3)*-1);
    }
return suma

  }
  public calcularEenPd(lista:any[]):number{
    let suma:number=0
    if(lista[101]>0){
      suma=suma+(lista[101]-1);
    }
    if(lista[162]>0){
      suma=suma+(lista[162]-1);
    }
    if(lista[2]>0){
      suma=suma+((lista[2]-3)*-1);
    }
    if(lista[35]>0){
      suma=suma+((lista[35]-3)*-1);
    }
    if(lista[37]>0){
      suma=suma+((lista[37]-3)*-1);
    }
    if(lista[65]>0){
      suma=suma+((lista[65]-3)*-1);
    }
    if(lista[98]>0){
      suma=suma+((lista[98]-3)*-1);
    }
    if(lista[129]>0){
      suma=suma+((lista[129]-3)*-1);
    }
    if(lista[131]>0){
      suma=suma+((lista[131]-3)*-1);
    }
    if(lista[164]>0){
      suma=suma+((lista[164]-3)*-1);
    }
return suma

  }
  public calcularFenPd(lista:any[]):number{
    let suma:number=0
    if(lista[5]>0){
      suma=suma+(lista[5]-1);
    }
    if(lista[36]>0){
      suma=suma+(lista[36]-1);
    }
    if(lista[69]>0){
      suma=suma+(lista[69]-1);
    }
    if(lista[163]>0){
      suma=suma+(lista[35]-1);
    }
    if(lista[3]>0){
      suma=suma+((lista[3]-3)*-1);
    }
    if(lista[38]>0){
      suma=suma+((lista[38]-3)*-1);
    }
    if(lista[67]>0){
      suma=suma+((lista[67]-3)*-1);
    }
    if(lista[99]>0){
      suma=suma+((lista[99]-3)*-1);
    }
    if(lista[102]>0){
      suma=suma+((lista[102]-3)*-1);
    }
    if(lista[133]>0){
      suma=suma+((lista[133]-3)*-1);
    }
return suma

  }
  public calcularGenPd(lista:any[]):number{
    let suma:number=0
    if(lista[71]>0){
      suma=suma+(lista[71]-1);
    }
    if(lista[105]>0){
      suma=suma+(lista[105]-1);
    }
    if(lista[132]>0){
      suma=suma+(lista[132]-1);
    }
    if(lista[135]>0){
      suma=suma+(lista[135]-1);
    }
    if(lista[165]>0){
      suma=suma+(lista[165]-1);
    }
    if(lista[4]>0){
      suma=suma+((lista[4]-3)*-1);
    }
    if(lista[6]>0){
      suma=suma+((lista[6]-3)*-1);
    }
    if(lista[39]>0){
      suma=suma+((lista[39]-3)*-1);
    }
    if(lista[68]>0){
      suma=suma+((lista[68]-3)*-1);
    }
    if(lista[103]>0){
      suma=suma+((lista[103]-3)*-1);
    }
    if(lista[167]>0){
      suma=suma+((lista[167]-3)*-1);
    }
return suma

  }
  public calcularHenPd(lista:any[]):number{
    let suma:number=0
    if(lista[40]>0){
      suma=suma+(lista[40]-1);
    }
    if(lista[70]>0){
      suma=suma+(lista[70]-1);
    }
    if(lista[104]>0){
      suma=suma+(lista[104]-1);
    }
    if(lista[106]>0){
      suma=suma+(lista[106]-1);
    }
    if(lista[166]>0){
      suma=suma+(lista[166]-1);
    }
    if(lista[168]>0){
      suma=suma+(lista[168]-1);
    }
    if(lista[8]>0){
      suma=suma+((lista[8]-3)*-1);
    }
    if(lista[72]>0){
      suma=suma+((lista[72]-3)*-1);
    }
    if(lista[134]>0){
      suma=suma+((lista[134]-3)*-1);
    }
    if(lista[136]>0){
      suma=suma+((lista[136]-3)*-1);
    }
return suma

  }
  public calcularIenPd(lista:any[]):number{
    let suma:number=0
    if(lista[6]>0){
      suma=suma+(lista[8]-1);
    }
    if(lista[109]>0){
      suma=suma+(lista[109]-1);
    }
    if(lista[137]>0){
      suma=suma+(lista[137]-1);
    }
    if(lista[139]>0){
      suma=suma+(lista[139]-1);
    }
    if(lista[169]>0){
      suma=suma+(lista[169]-1);
    }
    if(lista[9]>0){
      suma=suma+((lista[9]-3)*-1);
    }
    if(lista[41]>0){
      suma=suma+((lista[41]-3)*-1);
    }
    if(lista[43]>0){
      suma=suma+((lista[43]-3)*-1);
    }
    if(lista[73]>0){
      suma=suma+((lista[73]-3)*-1);
    }
    if(lista[76]>0){
      suma=suma+((lista[76]-3)*-1);
    }
    if(lista[107]>0){
      suma=suma+((lista[107]-3)*-1);
    }
return suma

  }
  public calcularLenPd(lista:any[]):number{
    let suma:number=0
    if(lista[44]>0){
      suma=suma+(lista[44]-1);
    }
    if(lista[77]>0){
      suma=suma+(lista[77]-1);
    }
    if(lista[108]>0){
      suma=suma+(lista[108]-1);
    }
    if(lista[138]>0){
      suma=suma+(lista[138]-1);
    }
    if(lista[10]>0){
      suma=suma+((lista[10]-3)*-1);
    }
    if(lista[12]>0){
      suma=suma+((lista[12]-3)*-1);
    }
    if(lista[42]>0){
      suma=suma+((lista[42]-3)*-1);
    }
    if(lista[75]>0){
      suma=suma+((lista[75]-3)*-1);
    }
    if(lista[111]>0){
      suma=suma+((lista[111]-3)*-1);
    }
    if(lista[140]>0){
      suma=suma+((lista[140]-3)*-1);
    }
return suma

  }
  public calcularMenPd(lista:any[]):number{
    let suma:number=0
    if(lista[16]>0){
      suma=suma+(lista[16]-1);
    }
    if(lista[45]>0){
      suma=suma+(lista[45]-1);
    }
    if(lista[48]>0){
      suma=suma+(lista[48]-1);
    }
    if(lista[80]>0){
      suma=suma+(lista[80]-1);
    }
    if(lista[113]>0){
      suma=suma+(lista[113]-1);
    }
    if(lista[11]>0){
      suma=suma+((lista[11]-3)*-1);
    }
    if(lista[13]>0){
      suma=suma+((lista[13]-3)*-1);
    }
    if(lista[78]>0){
      suma=suma+((lista[78]-3)*-1);
    }
    if(lista[110]>0){
      suma=suma+((lista[110]-3)*-1);
    }
    if(lista[141]>0){
      suma=suma+((lista[141]-3)*-1);
    }
    if(lista[144]>0){
      suma=suma+((lista[144]-3)*-1);
    }
return suma

  }
  public calcularNenPd(lista:any[]):number{
    let suma:number=0
    if(lista[14]>0){
      suma=suma+(lista[14]-1);
    }
    if(lista[17]>0){
      suma=suma+(lista[64]-1);
    }
    if(lista[83]>0){
      suma=suma+(lista[83]-1);
    }
    if(lista[116]>0){
      suma=suma+(lista[116]-1);
    }
    if(lista[46]>0){
      suma=suma+((lista[46]-3)*-1);
    }
    if(lista[49]>0){
      suma=suma+((lista[49]-3)*-1);
    }
    if(lista[79]>0){
      suma=suma+((lista[79]-3)*-1);
    }
    if(lista[112]>0){
      suma=suma+((lista[112]-3)*-1);
    }
    if(lista[142]>0){
      suma=suma+((lista[142]-3)*-1);
    }
    if(lista[147]>0){
      suma=suma+((lista[147]-3)*-1);
    }
return suma

  }
  public calcularOenPd(lista:any[]):number{
    let suma:number=0
    if(lista[18]>0){
      suma=suma+(lista[18]-1);
    }
    if(lista[20]>0){
      suma=suma+(lista[20]-1);
    }
    if(lista[81]>0){
      suma=suma+(lista[81]-1);
    }
    if(lista[118]>0){
      suma=suma+(lista[118]-1);
    }
    if(lista[50]>0){
      suma=suma+((lista[50]-3)*-1);
    }
    if(lista[53]>0){
      suma=suma+((lista[53]-3)*-1);
    }
    if(lista[86]>0){
      suma=suma+((lista[86]-3)*-1);
    }
    if(lista[115]>0){
      suma=suma+((lista[115]-3)*-1);
    }
    if(lista[145]>0){
      suma=suma+((lista[145]-3)*-1);
    }
    if(lista[149]>0){
      suma=suma+((lista[149]-3)*-1);
    }
return suma

  }
  public calcularQ1enPd(lista:any[]):number{
    let suma:number=0
    if(lista[23]>0){
      suma=suma+(lista[23]-1);
    }
    if(lista[51]>0){
      suma=suma+(lista[51]-1);
    }
    if(lista[54]>0){
      suma=suma+(lista[54]-1);
    }
    if(lista[85]>0){
      suma=suma+(lista[85]-1);
    }
    if(lista[146]>0){
      suma=suma+(lista[146]-1);
    }
    if(lista[150]>0){
      suma=suma+(lista[150]-1);
    }
    if(lista[19]>0){
      suma=suma+((lista[19]-3)*-1);
    }
    if(lista[21]>0){
      suma=suma+((lista[21]-3)*-1);
    }
    if(lista[52]>0){
      suma=suma+((lista[52]-3)*-1);
    }
    if(lista[82]>0){
      suma=suma+((lista[82]-3)*-1);
    }
    if(lista[87]>0){
      suma=suma+((lista[87]-3)*-1);
    }
    if(lista[117]>0){
      suma=suma+((lista[117]-3)*-1);
    }
    if(lista[119]>0){
      suma=suma+((lista[119]-3)*-1);
    }
    if(lista[148]>0){
      suma=suma+((lista[148]-3)*-1);
    }

return suma

  }
  public calcularQ2enPd(lista:any[]):number{
    let suma:number=0
    if(lista[24]>0){
      suma=suma+(lista[24]-1);
    }
    if(lista[55]>0){
      suma=suma+(lista[55]-1);
    }
    if(lista[91]>0){
      suma=suma+(lista[91]-1);
    }
    if(lista[122]>0){
      suma=suma+(lista[122]-1);
    }
    if(lista[155]>0){
      suma=suma+(lista[155]-1);
    }
    if(lista[26]>0){
      suma=suma+((lista[26]-3)*-1);
    }
    if(lista[58]>0){
      suma=suma+((lista[58]-3)*-1);
    }
    if(lista[88]>0){
      suma=suma+((lista[88]-3)*-1);
    }
    if(lista[120]>0){
      suma=suma+((lista[120]-3)*-1);
    }
    if(lista[151]>0){
      suma=suma+((lista[151]-3)*-1);
    }
    
return suma

  }
  public calcularQ3enPd(lista:any[]):number{
    let suma:number=0
    if(lista[25]>0){
      suma=suma+(lista[25]-1);
    }
    if(lista[28]>0){
      suma=suma+(lista[28]-1);
    }
    if(lista[56]>0){
      suma=suma+(lista[56]-1);
    }
    if(lista[89]>0){
      suma=suma+(lista[89]-1);
    }
    if(lista[121]>0){
      suma=suma+(lista[121]-1);
    }
    if(lista[153]>0){
      suma=suma+(lista[153]-1);
    }
    if(lista[60]>0){
      suma=suma+((lista[60]-3)*-1);
    }
    if(lista[92]>0){
      suma=suma+((lista[92]-3)*-1);
    }
    if(lista[124]>0){
      suma=suma+((lista[124]-3)*-1);
    }
    if(lista[156]>0){
      suma=suma+((lista[156]-3)*-1);
    }
    
return suma

  }
  public calcularQ4enPd(lista:any[]):number{
    let suma:number=0
    if(lista[59]>0){
      suma=suma+(lista[59]-1);
    }
    if(lista[90]>0){
      suma=suma+(lista[90]-1);
    }
    if(lista[93]>0){
      suma=suma+(lista[93]-1);
    }
    if(lista[123]>0){
      suma=suma+(lista[123]-1);
    }
    if(lista[27]>0){
      suma=suma+((lista[27]-3)*-1);
    }
    if(lista[29]>0){
      suma=suma+((lista[29]-3)*-1);
    }
    if(lista[61]>0){
      suma=suma+((lista[61]-3)*-1);
    }
    if(lista[125]>0){
      suma=suma+((lista[125]-3)*-1);
    }
    if(lista[154]>0){
      suma=suma+((lista[154]-3)*-1);
    }
    if(lista[157]>0){
      suma=suma+((lista[157]-3)*-1);
    }
return suma

  }
  public calcularMIenPd(lista:any[]):number{
    let suma:number=0
    if(lista[17]>0){
      suma=suma+(lista[17]-1);
    }
    if(lista[22]>0){
      suma=suma+(lista[22]-1);
    }
    if(lista[47]>0){
      suma=suma+(lista[47]-1);
    }
    if(lista[57]>0){
      suma=suma+(lista[57]-1);
    }
    if(lista[74]>0){
      suma=suma+(lista[74]-1);
    }
    if(lista[84]>0){
      suma=suma+(lista[84]-1);;
    }
    if(lista[94]>0){
      suma=suma+(lista[94]-1);;
    }
    if(lista[100]>0){
      suma=suma+(lista[100]-1);;
    }
    if(lista[114]>0){
      suma=suma+(lista[114]-1);
    }
    if(lista[143]>0){
      suma=suma+(lista[143]-1);
    }
    if(lista[33]>0){
      suma=suma+(lista[33]-1);
    }
    if(lista[152]>0){
      suma=suma+(lista[152]-1);
    }
return suma

  }
  public calcularINenPd(lista:any[]):number{
    let suma:number=0
    if(lista[6]==2){
      suma=suma+1;
    }
    if(lista[9]==2){
      suma=suma+1;
    }
    if(lista[11]==2){
      suma=suma+1;
    }
    if(lista[15]==2){
      suma=suma+1;
    }
    if(lista[17]==2){
      suma=suma+1;
    }
    if(lista[21]==2){
      suma=suma+1;
    }
    if(lista[23]==2){
      suma=suma+1;
    }
    if(lista[25]==2){
      suma=suma+1;
    }
    if(lista[26]==2){
      suma=suma+1;
    }
    if(lista[27]==2){
      suma=suma+1;
    }
    if(lista[34]==2){
      suma=suma+1;
    }
    if(lista[35]==2){
      suma=suma+1;
    }
    if(lista[50]==2){
      suma=suma+1;
    }
    if(lista[55]==2){
      suma=suma+1;
    }
    if(lista[62]==2){
      suma=suma+1;
    }
    if(lista[74]==2){
      suma=suma+1;
    }
    if(lista[79]==2){
      suma=suma+1;
    }
    if(lista[84]==2){
      suma=suma+1;
    }
    if(lista[89]==2){
      suma=suma+1;
    }
    if(lista[90]==2){
      suma=suma+1;
    }
    if(lista[91]==2){
      suma=suma+1;
    }
    if(lista[97]==2){
      suma=suma+1;
    }
    if(lista[100]==2){
      suma=suma+1;
    }
    if(lista[101]==2){
      suma=suma+1;
    }
    if(lista[110]==2){
      suma=suma+1;
    }
    if(lista[115]==2){
      suma=suma+1;
    }
    if(lista[120]==2){
      suma=suma+1;
    }
    if(lista[122]==2){
      suma=suma+1;
    }
    if(lista[124]==2){
      suma=suma+1;
    }
    if(lista[127]==2){
      suma=suma+1;
    }
    if(lista[129]==2){
      suma=suma+1;
    }
    if(lista[130]==2){
      suma=suma+1;
    }
    if(lista[139]==2){
      suma=suma+1;
    }
    if(lista[143]==2){
      suma=suma+1;
    }
    if(lista[150]==2){
      suma=suma+1;
    }
    if(lista[153]==2){
      suma=suma+1;
    }
    if(lista[157]==2){
      suma=suma+1;
    }
    if(lista[159]==2){
      suma=suma+1;
    }
return suma

  }
  public calcularQAenPd(lista:any[]):number{
    let suma:number=0
    if(lista[1]==1){
      suma=suma+1;
    }
    if(lista[3]==1){
      suma=suma+1;
    }
    if(lista[4]==1){
      suma=suma+1;
    }
    if(lista[5]==1){
      suma=suma+1;
    }
    if(lista[8]==1){
      suma=suma+1;
    }
    if(lista[9]==1){
      suma=suma+1;
    }
    if(lista[11]==1){
      suma=suma+1;
    }
    if(lista[12]==1){
      suma=suma+1;
    }
    if(lista[13]==1){
      suma=suma+1;
    }
    if(lista[22]==1){
      suma=suma+1;
    }
    if(lista[26]==1){
      suma=suma+1;
    }
    if(lista[27]==1){
      suma=suma+1;
    }
    if(lista[28]==1){
      suma=suma+1;
    }
    if(lista[32]==1){
      suma=suma+1;
    }
    if(lista[33]==1){
      suma=suma+1;
    }
    if(lista[34]==1){
      suma=suma+1;
    }
    if(lista[35]==1){
      suma=suma+1;
    }
    if(lista[38]==1){
      suma=suma+1;
    }
    if(lista[39]==1){
      suma=suma+1;
    }
    if(lista[40]==1){
      suma=suma+1;
    }
    if(lista[42]==1){
      suma=suma+1;
    }
    if(lista[43]==1){
      suma=suma+1;
    }
    if(lista[46]==1){
      suma=suma+1;
    }
    if(lista[47]==1){
      suma=suma+1;
    }
    if(lista[48]==1){
      suma=suma+1;
    }
    if(lista[49]==1){
      suma=suma+1;
    }
    if(lista[53]==1){
      suma=suma+1;
    }
    if(lista[56]==1){
      suma=suma+1;
    }
    if(lista[57]==1){
      suma=suma+1;
    }
    if(lista[58]==1){
      suma=suma+1;
    }
    if(lista[60]==1){
      suma=suma+1;
    }
    if(lista[61]==1){
      suma=suma+1;
    }
    if(lista[62]==1){
      suma=suma+1;
    }
    if(lista[63]==1){
      suma=suma+1;
    }
    if(lista[64]==1){
      suma=suma+1;
    }
    if(lista[65]==1){
      suma=suma+1;
    }
    if(lista[67]==1){
      suma=suma+1;
    }
    if(lista[68]==1){
      suma=suma+1;
    }
    if(lista[70]==1){
      suma=suma+1;
    }
    if(lista[75]==1){
      suma=suma+1;
    }
    if(lista[76]==1){
      suma=suma+1;
    }
    if(lista[78]==1){
      suma=suma+1;
    }
    if(lista[82]==1){
      suma=suma+1;
    }
    if(lista[84]==1){
      suma=suma+1;
    }
    if(lista[86]==1){
      suma=suma+1;
    }
    if(lista[88]==1){
      suma=suma+1;
    }
    if(lista[89]==1){
      suma=suma+1;
    }
    if(lista[90]==1){
      suma=suma+1;
    }
    if(lista[91]==1){
      suma=suma+1;
    }
    if(lista[92]==1){
      suma=suma+1;
    }
    if(lista[95]==1){
      suma=suma+1;
    }
    if(lista[96]==1){
      suma=suma+1;
    }
    if(lista[98]==1){
      suma=suma+1;
    }
    if(lista[99]==1){
      suma=suma+1;
    }
    if(lista[102]==1){
      suma=suma+1;
    }
    if(lista[104]==1){
      suma=suma+1;
    }
    if(lista[105]==1){
      suma=suma+1;
    }
    if(lista[106]==1){
      suma=suma+1;
    }
    if(lista[107]==1){
      suma=suma+1;
    }
    if(lista[109]==1){
      suma=suma+1;
    }
    if(lista[110]==1){
      suma=suma+1;
    }
    if(lista[112]==1){
      suma=suma+1;
    }
    if(lista[113]==1){
      suma=suma+1;
    }
    if(lista[115]==1){
      suma=suma+1;
    }
    if(lista[116]==1){
      suma=suma+1;
    }
    if(lista[117]==1){
      suma=suma+1;
    }
    if(lista[123]==1){
      suma=suma+1;
    }
    if(lista[124]==1){
      suma=suma+1;
    }
    if(lista[125]==1){
      suma=suma+1;
    }
    if(lista[127]==1){
      suma=suma+1;
    }
    if(lista[129]==1){
      suma=suma+1;
    }
    if(lista[131]==1){
      suma=suma+1;
    }
    if(lista[132]==1){
      suma=suma+1;
    }
    if(lista[133]==1){
      suma=suma+1;
    }
    if(lista[134]==1){
      suma=suma+1;
    }
    if(lista[136]==1){
      suma=suma+1;
    }
    if(lista[137]==1){
      suma=suma+1;
    }
    if(lista[140]==1){
      suma=suma+1;
    }
    if(lista[141]==1){
      suma=suma+1;
    }
    if(lista[144]==1){
      suma=suma+1;
    }
    if(lista[145]==1){
      suma=suma+1;
    }
    if(lista[147]==1){
      suma=suma+1;
    }
    if(lista[148]==1){
      suma=suma+1;
    }
    if(lista[149]==1){
      suma=suma+1;
    }
    if(lista[150]==1){
      suma=suma+1;
    }
    if(lista[151]==1){
      suma=suma+1;
    }
    if(lista[154]==1){
      suma=suma+1;
    }
    if(lista[155]==1){
      suma=suma+1;
    }
    if(lista[156]==1){
      suma=suma+1;
    }
    if(lista[158]==1){
      suma=suma+1;
    }
    if(lista[160]==1){
      suma=suma+1;
    }
    if(lista[164]==1){
      suma=suma+1;
    }
    if(lista[165]==1){
      suma=suma+1;
    }
    if(lista[166]==1){
      suma=suma+1;
    }
    if(lista[168]==1){
      suma=suma+1;
    }
    
return suma

  }

}
